name: Guardian Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install dependencies
        run: npm
      - name: Install playwright browsers
        run: npm playwright install --with-deps
      - name: Run Guardian tests
        run: |
          npm tsx tests/getRTokens.ts > tests/RTokens.json
          npm test:e2e
        env:
          CI: true
          VITE_WALLETCONNECT_ID: ${{ secrets.WALLETCONNECT_ID }}
          VITE_ALCHEMY: ${{ secrets.ALCHEMY }}
          GUARDIAN_UI_ALCHEMY_API_KEY: ${{ secrets.ALCHEMY }}
          GUARDIAN_UI_ANVIL_FLAGS: '--compute-units-per-second 100 --fork-retry-backoff 5000'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
